channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=24.2
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.0
  - numpy==1.24.4
  - pandas==2.0.3
  - psutil==5.9.8
  - scikit-learn==1.2.0
  - scipy==1.10.1
  - xgboost==2.0.3
name: mlflow-env
